export const PROJECTS = [
  {
    id: "pr-1",
    title: "Медиастена Dubai Mall",
    city: "Дубай",
    area: 140,
    pitch: 2.5,
    place: "Торговый центр · indoor LED wall",
    hue: 210,
    image: "/led/project-dubai-mall.png",
  },
  {
    id: "pr-2",
    title: "Цифровые билборды Times Square",
    city: "Нью-Йорк",
    area: 320,
    pitch: 10,
    place: "DOOH · Absen / outdoor A Series",
    hue: 195,
    image: "/led/project-times-square.png",
  },
  {
    id: "pr-3",
    title: "3D-медиафасад IFS",
    city: "Чэнду",
    area: 4000,
    pitch: 6,
    place: "Naked-eye 3D · Unilumin",
    hue: 320,
    image: "/led/project-ifs.png",
  },
  {
    id: "pr-4",
    title: "LED-стены выставки ISE",
    city: "Барселона",
    area: 86,
    pitch: 1.5,
    place: "Конференц / show · Uslim / TVF",
    hue: 230,
    image: "/led/project-conf.jpg",
  },
  {
    id: "pr-5",
    title: "Витрина Unilumin U-Glass",
    city: "Шанхай",
    area: 48,
    pitch: 3,
    place: "Ритейл · прозрачный LED",
    hue: 250,
    image: "/led/transparent.jpg",
  },
  {
    id: "pr-6",
    title: "Главная сцена Coachella",
    city: "Индио",
    area: 220,
    pitch: 2.5,
    place: "Rental · Upad IV / PL Pro",
    hue: 265,
    image: "/led/project-stage.jpg",
  },
]

export const CITIES = [
  "Душанбе",
  "Худжанд",
  "Бохтар",
  "Куляб",
  "Истаравшан",
  "Пенджикент",
  "Хорог",
  "Турсунзаде",
]
