import type { LedCategory, PixelPitch, Product } from "@/lib/types"

export const CATEGORY_LABEL: Record<LedCategory, string> = {
  indoor: "Интерьерные (Indoor)",
  outdoor: "Уличные (Outdoor)",
  transparent: "Прозрачные (Transparent)",
  rental: "Сценические (Rental)",
  flexible: "Гибкие (Flexible)",
}

export const PITCH_OPTIONS: PixelPitch[] = [
  1.2, 1.5, 1.8, 2, 2.5, 2.6, 3, 3.9, 4, 5, 6.6, 10,
]

export const PRODUCTS: Product[] = [
  {
    id: "p-indoor-12",
    slug: "indoor-p1-2-studio",
    name: "Absen KLCOB P1.2",
    category: "indoor",
    pitch: 1.2,
    brightness: 800,
    ipRating: "IP31",
    cabinetMm: [500, 500],
    cabinetResolution: [416, 416],
    powerPerM2: 420,
    pricePerM2Tjs: 20350,
    inStock: true,
    hit: true,
    unit: "m2",
    hue: 210,
    image: "/led/absen-klcob-p12.png",
    description:
      "COB-кабинет Absen для студий и переговорных. Шаг 1,2 мм, 800 нит, кабинет 500×500 мм — как в официальной линейке KLCOB.",
  },
  {
    id: "p-indoor-15",
    slug: "indoor-p1-5-boardroom",
    name: "Unilumin Uslim III P1.5",
    category: "indoor",
    pitch: 1.5,
    brightness: 800,
    ipRating: "IP31",
    cabinetMm: [600, 337],
    cabinetResolution: [400, 224],
    powerPerM2: 380,
    pricePerM2Tjs: 11100,
    inStock: true,
    hit: true,
    unit: "m2",
    hue: 200,
    image: "/led/unilumin-uslim-iii.png",
    description:
      "Тонкий indoor Unilumin Uslim III. 16:9, 800 нит — типичный экран для конференц-залов и ситуационных центров.",
  },
  {
    id: "p-indoor-18",
    slug: "indoor-p1-8-retail",
    name: "Leyard TVF P1.8",
    category: "indoor",
    pitch: 1.8,
    brightness: 800,
    ipRating: "IP31",
    cabinetMm: [608, 342],
    cabinetResolution: [336, 189],
    powerPerM2: 390,
    pricePerM2Tjs: 9250,
    inStock: true,
    hit: false,
    unit: "m2",
    hue: 190,
    image: "/led/leyard-tvf-p18.png",
    description:
      "Fine-pitch Leyard TVF для ритейла и медиастен. Шаг 1,8 мм, фронтальный сервис, кабинет 27″ класса.",
  },
  {
    id: "p-indoor-2",
    slug: "indoor-p2-lobby",
    name: "Absen Polaris P2",
    category: "indoor",
    pitch: 2,
    brightness: 1000,
    ipRating: "IP31",
    cabinetMm: [500, 500],
    cabinetResolution: [250, 250],
    powerPerM2: 380,
    pricePerM2Tjs: 6010,
    inStock: true,
    hit: true,
    unit: "m2",
    hue: 222,
    image: "/led/absen-polaris.png",
    description:
      "Универсальный indoor Absen Polaris. 1000 нит, 500×500 мм — холлы, рестораны, корпоративные стены.",
  },
  {
    id: "p-indoor-25",
    slug: "indoor-p2-5-gallery",
    name: "Absen PL2.5 Plus V2",
    category: "indoor",
    pitch: 2.5,
    brightness: 1200,
    ipRating: "IP31",
    cabinetMm: [500, 500],
    cabinetResolution: [200, 200],
    powerPerM2: 360,
    pricePerM2Tjs: 3890,
    inStock: true,
    hit: false,
    unit: "m2",
    hue: 230,
    image: "/led/absen-pl25-plus.png",
    description:
      "Серия Absen PL Plus V2: 500×500 мм, 200×200 пикселей, 1200 нит, refresh 7680 Гц — как в спецификации 2024.",
  },
  {
    id: "p-outdoor-3",
    slug: "outdoor-p3-facade",
    name: "Unilumin Upanel 2 P3",
    category: "outdoor",
    pitch: 3,
    brightness: 5500,
    ipRating: "IP65",
    cabinetMm: [960, 960],
    cabinetResolution: [320, 320],
    powerPerM2: 780,
    pricePerM2Tjs: 10180,
    inStock: true,
    hit: true,
    unit: "m2",
    hue: 195,
    image: "/led/unilumin-upanel.png",
    description:
      "Уличный Upanel 2. IP65, ~5500 нит — медиафасады и городские экраны с близкой дистанцией просмотра.",
  },
  {
    id: "p-outdoor-4",
    slug: "outdoor-p4-city",
    name: "Absen A Series P4",
    category: "outdoor",
    pitch: 4,
    brightness: 7500,
    ipRating: "IP65",
    cabinetMm: [1280, 960],
    cabinetResolution: [320, 240],
    powerPerM2: 800,
    pricePerM2Tjs: 8330,
    inStock: true,
    hit: true,
    unit: "m2",
    hue: 205,
    image: "/led/absen-a-series-p4.png",
    description:
      "Наружная линейка Absen A Series. Кабинет 1280×960 мм, 7500 нит — формат городских медиабордов.",
  },
  {
    id: "p-outdoor-5",
    slug: "outdoor-p5-highway",
    name: "Unilumin Usurface P5",
    category: "outdoor",
    pitch: 5,
    brightness: 6500,
    ipRating: "IP65",
    cabinetMm: [960, 960],
    cabinetResolution: [192, 192],
    powerPerM2: 820,
    pricePerM2Tjs: 6010,
    inStock: true,
    hit: false,
    unit: "m2",
    hue: 215,
    image: "/led/unilumin-usurface-p5.png",
    description:
      "Usurface для трасс и площадей. Дальняя дистанция, высокий запас яркости, полный outdoor IP65.",
  },
  {
    id: "p-outdoor-6",
    slug: "outdoor-p6-plaza",
    name: "Absen A Series P6.6",
    category: "outdoor",
    pitch: 6.6,
    brightness: 7500,
    ipRating: "IP65",
    cabinetMm: [1280, 960],
    cabinetResolution: [192, 144],
    powerPerM2: 850,
    pricePerM2Tjs: 4630,
    inStock: true,
    hit: false,
    unit: "m2",
    hue: 185,
    image: "/led/absen-a-series-p66.png",
    description:
      "Absen A Series P6.66 из спецификации 2024: 1280×960 мм, 7500 нит, SMD 2727 — крупные медиафасады.",
  },
  {
    id: "p-outdoor-10",
    slug: "outdoor-p10-billboard",
    name: "Absen A Series P10",
    category: "outdoor",
    pitch: 10,
    brightness: 7500,
    ipRating: "IP65",
    cabinetMm: [1280, 960],
    cabinetResolution: [128, 96],
    powerPerM2: 700,
    pricePerM2Tjs: 3520,
    inStock: true,
    hit: false,
    unit: "m2",
    hue: 175,
    image: "/led/absen-a-series-p10.png",
    description:
      "Билборд Absen A Series P10: 1280×960 мм, 128×96 пикселей, 7500 нит — экономичный outdoor на дальнюю дистанцию.",
  },
  {
    id: "p-trans-38",
    slug: "transparent-p3-8-glass",
    name: "Unilumin U-Glass P3.9",
    category: "transparent",
    pitch: 3.9,
    brightness: 5000,
    ipRating: "IP54",
    cabinetMm: [1000, 500],
    cabinetResolution: [256, 128],
    powerPerM2: 320,
    pricePerM2Tjs: 8790,
    inStock: true,
    hit: true,
    unit: "m2",
    hue: 250,
    image: "/led/unilumin-uglass.png",
    description:
      "Прозрачная сетка Unilumin U-Glass. Свет проходит сквозь экран — витрины бутиков и стеклянные фасады.",
  },
  {
    id: "p-rental-29",
    slug: "rental-p2-9-stage",
    name: "Unilumin Upad IV P2.6",
    category: "rental",
    pitch: 2.6,
    brightness: 4500,
    ipRating: "IP65",
    cabinetMm: [500, 500],
    cabinetResolution: [192, 192],
    powerPerM2: 640,
    pricePerM2Tjs: 4160,
    inStock: true,
    hit: true,
    unit: "cabinet",
    hue: 265,
    image: "/led/unilumin-upad-iv.png",
    description:
      "Туринговый Upad IV. Литой кабинет 500×500, IP65, быстрые замки — концерты и корпоративные сцены.",
  },
  {
    id: "p-rental-39",
    slug: "rental-p3-9-tour",
    name: "Absen PL 3.9 Pro V2",
    category: "rental",
    pitch: 3.9,
    brightness: 5000,
    ipRating: "IP65",
    cabinetMm: [500, 500],
    cabinetResolution: [128, 128],
    powerPerM2: 680,
    pricePerM2Tjs: 3240,
    inStock: true,
    hit: false,
    unit: "cabinet",
    hue: 280,
    image: "/led/absen-pl39-pro.png",
    description:
      "Прокатный Absen PL Pro V2. 500×500 мм, высокая яркость и защита — фестивали и уличные ивенты.",
  },
  {
    id: "p-flex-2",
    slug: "flexible-p2-curve",
    name: "Unilumin Flexible P2",
    category: "flexible",
    pitch: 2,
    brightness: 1000,
    ipRating: "IP31",
    cabinetMm: [256, 128],
    cabinetResolution: [128, 64],
    powerPerM2: 410,
    pricePerM2Tjs: 7400,
    inStock: true,
    hit: false,
    unit: "m2",
    hue: 320,
    image: "/led/unilumin-flexible-p2.png",
    description:
      "Гибкий модуль Unilumin для колонн и арок. Гнётся без видимой сетки — брендовые зоны и шоурумы.",
  },
  {
    id: "p-flex-25",
    slug: "flexible-p2-5-wave",
    name: "Absen Flexible P2.5",
    category: "flexible",
    pitch: 2.5,
    brightness: 1200,
    ipRating: "IP31",
    cabinetMm: [320, 160],
    cabinetResolution: [128, 64],
    powerPerM2: 390,
    pricePerM2Tjs: 5370,
    inStock: false,
    hit: false,
    unit: "m2",
    hue: 330,
    image: "/led/absen-flexible-p25.png",
    description:
      "Мягкий Absen P2.5 для волн и радиусов. Под заказ 7–14 дней, монтаж по Таджикистану.",
  },
]

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug)
}

export function priceBounds() {
  const prices = PRODUCTS.map((p) => p.pricePerM2Tjs)
  return { min: Math.min(...prices), max: Math.max(...prices) }
}

export function brightnessBounds() {
  const values = PRODUCTS.map((p) => p.brightness)
  return { min: Math.min(...values), max: Math.max(...values) }
}
